/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface TesterInterface extends ethers.utils.Interface {
  functions: {
    "doIt()": FunctionFragment;
    "implementer()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "doIt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "implementer",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "doIt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "implementer",
    data: BytesLike
  ): Result;

  events: {
    "LayerTransferEvent(uint16,uint16)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LayerTransferEvent"): EventFragment;
}

export class Tester extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TesterInterface;

  functions: {
    doIt(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    implementer(overrides?: CallOverrides): Promise<[string]>;
  };

  doIt(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  implementer(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    doIt(overrides?: CallOverrides): Promise<void>;

    implementer(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    LayerTransferEvent(
      src?: BigNumberish | null,
      dst?: BigNumberish | null
    ): TypedEventFilter<[number, number], { src: number; dst: number }>;
  };

  estimateGas: {
    doIt(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    implementer(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    doIt(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    implementer(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
